# Generated by Django 4.1.5 on 2023-01-18 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_new_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_post',
            name='likes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='new_post',
            name='comment_field',
            field=models.TextField(max_length=1000),
        ),
    ]
