# Generated by Django 4.1.5 on 2023-01-18 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_new_post_likes_alter_new_post_comment_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
