# Generated by Django 4.1.5 on 2023-01-21 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_post',
            name='likes',
        ),
        migrations.AddField(
            model_name='new_post',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
