# Generated by Django 4.1.3 on 2023-01-27 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_new_post_likes_new_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_post',
            old_name='comment_field',
            new_name='post_field',
        ),
    ]
